version: '1.29.2'

services:
	mariadb:
		container_name: mariadb
		image: mariadb:42
		init: true
		build:
			context: ./requirements/mariadb
			dockerfile: Dockerfile
			environment:
				- MYSQL_DATABASE: ${MYSQL_DATABASE}
				- MYSQL_USER: ${MYSQL_USER}
				- MYSQL_PASSWORD: ${MYSQL_PASSWORD}
				- MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
		networks:
			- inception
		volumes:
			- mariadb: var/lib/mysql
		restart: always

volumes:
	mariadb:
		name: mariadb
		external: true

networks:
	inception:
		name: inception
		driver: bridge