version: '2.2.3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

volumes:
  mariadb:
    name: mariadb
    external: true

networks:
  inception:
    name: inception
    driver: bridge