version: '2.2.3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    restart: always

volumes:
  mariadb:
    name: mariadb
    external: true
  wordpress:
    name: wordpress
    external: true

networks:
  inception:
    name: inception
    driver: bridge